language: node_js
node_js:
  - "0.8"
install:
  - "bin/installDeps.sh"
  - "export GIT_HASH=$(cat .git/HEAD | head -c 7)"
before_script: 
  - "tests/frontend/travis/sauce_tunnel.sh"
script:
  - "tests/frontend/travis/runner.sh"
env:
  global:
    - secure: "Y5c+H5P3b/W48UClURXAuAvQ4jcR/P5QF6hpwBQcFiLbWX6WPIZnxoxNkane\nyUYlytjcOxI/sqTP2liW0NX+7Q+RLAKmsyBXT8CLi4Rz/mpOjmJvMTnll8qe\nCYmO1eK4C/r9p7PW3cq97vFKnZykEX75ELdtaAFOsBaFiQLRRPs="
    - SAUCE_USER=pita
jdk:
  - oraclejdk6
notifications:
  email:
    - petermartischka@googlemail.com
  irc:
    channels:
      - "irc.freenode.org#etherpad-lite-dev"